name: Run Unit Tests

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - name: Setup memcached server
      uses: niden/actions-memcached@v7
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install -e .[all]
    - name: Run Tests
      run: |
        pytest
        
    - name: Build badges
      run: |
        flake8 src --output-file ci/flake8.txt
        genbadge coverage -i ci/coverage.xml -o ci/badges/coverage.svg
        genbadge tests -i ci/junit/junit.xml -o ci/badges/tests.svg
        genbadge flake8 -i ci/flake8.txt -o ci/badges/flake.svg

    - name: Upload badges
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        file_pattern: 'ci/badges/*.svg'

    build-win-mac:
      matrix:
        os: [windows-latest, macos-latest]
      runs-on: ${{ matrix.os }}
      steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -e .[all]
      - name: Run Tests
        run: |
          pytest
